agv_controller:
  ros__parameters:
    pid_update_rate: 100.0
    anti_windup: 0.3
    Kpx: 2.0
    Kdx: 0.1
    Kix: 0.01

    Kpy: 2.0
    Kdy: 0.1
    Kiy: 0.01

    Kpdtheta: 2.0
    Kddtheta: 0.001
    Kidtheta: 0.01




    Kpy: 2.1
    Kpdtheta: 2.0