<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
        xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
        xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
        xmlns:xacro="http://ros.org/wiki/xacro">

  <property name="M_PI" value="3.14159"/>.

  <xacro:include filename="$(find youbot_description)/urdf/sensors/asus_xtion_camera.gazebo.xacro" />
  
  <property name="eye_x_offset" value="0.03" />
  <property name="eye_y_offset" value="0.035" />
  
  <xacro:macro name="asus_xtion_eye" params="suffix parent *origin">
	<link name="${parent}_${suffix}_frame">
	  <inertial>
		<mass value="0.01" />
		<origin xyz="0 0 0" />
		<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
	  </inertial>	
	</link>
	
	<joint name="${parent}_${suffix}_joint" type="fixed">
	  <parent link="${parent}_camera"/>
	  <child link="${parent}_${suffix}_frame"/>
	  <insert_block name="origin"/>
	</joint>		
  </xacro:macro>



    
  <xacro:macro name="asus_xtion_camera" params="name parent *origin tilt">

    <link name="${name}_camera">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0.02 -0.03 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://youbot_description/meshes/sensors/asus_xtion_pro_live_camera.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Black" />
      </visual>

      <collision>
        <origin xyz="0.02 -0.03 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
        <geometry>
   	  <box size="0.2 0.06 0.07"/>       
<!-- 
	  <mesh filename="package://youbot_description/meshes/sensors/asus_xtion_pro_live_camera.dae" scale="0.001 0.001 0.001"/>
-->
        </geometry>
      </collision >
    </link>

    <joint name="${parent}_${name}_joint" type="fixed">
      <insert_block name="origin" />
      <parent link="${parent}" />
      <child link="${name}_camera" />
    </joint>
    
	<xacro:asus_xtion_eye suffix="depth" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.02} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
        
	<xacro:asus_xtion_eye suffix="depth_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.02} 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="rgb" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.04} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="rgb_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.04} 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="laser" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.09} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="laser_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.09} 0" rpy="${M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>

    
   <!-- for simulation 
   <xacro:asus_xtion_camera_gazebo name="${name}" />
  -->
  </xacro:macro>
<!--  <xacro:asus_xtion_camera name="xtion" tilt="0.0">
     <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:asus_xtion_camera>
-->	

</robot>
