
agv:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Speed Controllers ---------------------------------------
  wheel_fl_speed_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint_fl
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_fr_speed_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint_fr
    pid: {p: 100.0, i: 0.01, d: 10.0}

  wheel_bl_speed_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint_bl
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wheel_br_speed_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_joint_br
    pid: {p: 100.0, i: 0.01, d: 10.0}

